"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import ProvidersWrapper from "./ProvidersWrapper";
import HeaderFooter from "@/app/components/header_footer";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const { data, status } = useSession();
  // console.log("layout page", data, status);
  return (
    <html lang="en">
      <ProvidersWrapper>
        <body className={inter.className}>
          <HeaderFooter>
            <main>{children}</main>
          </HeaderFooter>
          <script
            id="googlemaps"
            type="text/javascript"
            strategy="beforeInteractive"
            //strategy="lazyOnload"
            src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_PLACES}&libraries=places`}
          ></script>
        </body>
      </ProvidersWrapper>
    </html>
  );
}
//