import "./globals.css";
import styles from "./home.module.css"
import { Inter } from "next/font/google";
import Image from "next/image"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <nav>
            <h2>
              EventLinkr
            </h2>
            <ul>
              <li>Home</li>
              <li>Dashboard</li>
              <li>Create Account</li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>Made with love</footer>
      </body>
    </html>
  );
}
